package com.harithkavish.keyboard;

/**
 * The emoji the picker offers, and the tab row across the bottom of it.
 *
 * <p>Written as backslash-u escapes rather than literals on purpose: the source
 * pure ASCII, so nothing here depends on the build agreeing with the editor
 * about file encoding. Each entry is one grapheme, which for a flag or a
 * variation-selector sequence is several chars -- never index into one.
 *
 * <p>Generated by tools/gen_emoji.py. Edit that, not this.
 */
final class Emoji {

    private Emoji() {
    }

    private static final String[] SMILEYS = {
        "\ud83d\ude00", "\ud83d\ude03", "\ud83d\ude04", "\ud83d\ude01", "\ud83d\ude06", "\ud83d\ude05",
        "\ud83e\udd23", "\ud83d\ude02", "\ud83d\ude42", "\ud83d\ude43", "\ud83d\ude09", "\ud83d\ude0a",
        "\ud83d\ude07", "\ud83e\udd70", "\ud83d\ude0d", "\ud83e\udd29", "\ud83d\ude18", "\ud83d\ude17",
        "\ud83d\ude1a", "\ud83d\ude19", "\ud83d\ude0b", "\ud83d\ude1b", "\ud83d\ude1c", "\ud83e\udd2a",
        "\ud83d\ude0e", "\ud83e\udd73", "\ud83d\ude0f", "\ud83d\ude12", "\ud83d\ude1e", "\ud83d\ude14",
        "\ud83d\ude1f", "\ud83d\ude25", "\ud83d\ude22", "\ud83d\ude2d", "\ud83d\ude31", "\ud83d\ude33",
        "\ud83e\udd7a", "\ud83d\ude24", "\ud83d\ude20", "\ud83d\ude21", "\ud83e\udd14", "\ud83e\udd2d",
        "\ud83e\udd2b", "\ud83e\udd10", "\ud83d\ude0c", "\ud83d\ude44", "\ud83d\ude2a", "\ud83d\ude34",
        "\ud83e\udd27", "\ud83e\udd12", "\ud83e\udd15", "\ud83e\udd11", "\ud83e\udd17", "\ud83d\ude36",
        "\ud83d\udc4d", "\ud83d\udc4e", "\ud83d\udc4c", "\u270c\ufe0f", "\ud83e\udd1e", "\ud83d\udc4f",
        "\ud83d\ude4f", "\ud83d\udcaa", "\ud83d\udc4b", "\ud83e\udd1d", "\u270d\ufe0f", "\ud83d\ude4c",
    };

    private static final String[] NATURE = {
        "\ud83d\udc36", "\ud83d\udc31", "\ud83d\udc2d", "\ud83d\udc39", "\ud83d\udc30", "\ud83e\udd8a",
        "\ud83d\udc3b", "\ud83d\udc3c", "\ud83d\udc28", "\ud83d\udc2f", "\ud83e\udd81", "\ud83d\udc2e",
        "\ud83d\udc37", "\ud83d\udc38", "\ud83d\udc12", "\ud83d\udc14", "\ud83d\udc27", "\ud83d\udc26",
        "\ud83d\udc1d", "\ud83e\udd8b", "\ud83d\udc1e", "\ud83d\udc22", "\ud83d\udc19", "\ud83d\udc20",
        "\ud83d\udc0b", "\ud83e\udd84", "\ud83c\udf32", "\ud83c\udf33", "\ud83c\udf34", "\ud83c\udf35",
        "\ud83c\udf3f", "\u2618\ufe0f", "\ud83c\udf40", "\ud83c\udf41", "\ud83c\udf42", "\ud83c\udf37",
        "\ud83c\udf38", "\ud83c\udf39", "\ud83c\udf3b", "\ud83c\udf3c", "\ud83d\udc90", "\ud83c\udf1e",
        "\ud83c\udf1d", "\ud83c\udf1a", "\u2b50", "\ud83c\udf1f", "\u2728", "\u26a1",
        "\ud83d\udd25", "\ud83c\udf08", "\u2601\ufe0f", "\u2744\ufe0f", "\ud83c\udf0a", "\ud83c\udf0d",
    };

    private static final String[] FOOD = {
        "\ud83c\udf4f", "\ud83c\udf4e", "\ud83c\udf50", "\ud83c\udf4a", "\ud83c\udf4b", "\ud83c\udf4c",
        "\ud83c\udf49", "\ud83c\udf47", "\ud83c\udf53", "\ud83c\udf52", "\ud83c\udf51", "\ud83e\udd6d",
        "\ud83c\udf45", "\ud83e\udd55", "\ud83c\udf3d", "\ud83e\udd54", "\ud83c\udf5e", "\ud83e\udd50",
        "\ud83e\udd56", "\ud83e\uddc0", "\ud83e\udd5a", "\ud83c\udf73", "\ud83e\udd53", "\ud83e\udd69",
        "\ud83c\udf57", "\ud83c\udf54", "\ud83c\udf5f", "\ud83c\udf55", "\ud83c\udf2d", "\ud83c\udf2e",
        "\ud83c\udf2f", "\ud83e\udd59", "\ud83e\udd58", "\ud83c\udf5d", "\ud83c\udf5c", "\ud83c\udf63",
        "\ud83c\udf71", "\ud83c\udf59", "\ud83c\udf58", "\ud83c\udf65", "\ud83c\udf68", "\ud83c\udf66",
        "\ud83c\udf70", "\ud83c\udf82", "\ud83c\udf6b", "\ud83c\udf6c", "\ud83c\udf6f", "\u2615",
        "\ud83c\udf75", "\ud83c\udf76", "\ud83c\udf7a", "\ud83c\udf7b", "\ud83c\udf77", "\ud83e\udd64",
    };

    private static final String[] ACTIVITY = {
        "\u26bd", "\ud83c\udfc0", "\ud83c\udfc8", "\u26be", "\ud83c\udfbe", "\ud83c\udfd0",
        "\ud83c\udfc9", "\ud83c\udfb1", "\ud83c\udfd3", "\ud83c\udff8", "\ud83e\udd4a", "\ud83c\udfaf",
        "\u26f3", "\ud83c\udfbf", "\ud83c\udfc2", "\ud83e\udd3c", "\ud83e\udd3a", "\ud83d\udeb4",
        "\ud83c\udfca", "\ud83e\uddd8", "\ud83c\udfc6", "\ud83e\udd47", "\ud83e\udd48", "\ud83e\udd49",
        "\ud83c\udfc5", "\ud83c\udfaa", "\ud83c\udfad", "\ud83c\udfa8", "\ud83c\udfac", "\ud83c\udfa4",
        "\ud83c\udfa7", "\ud83c\udfb5", "\ud83c\udfb6", "\ud83c\udfb9", "\ud83c\udfb7", "\ud83c\udfba",
        "\ud83c\udfb8", "\ud83c\udfbb", "\ud83c\udfb2", "\ud83c\udfae", "\ud83e\udd45", "\ud83c\udfaf",
    };

    private static final String[] TRAVEL = {
        "\ud83d\ude97", "\ud83d\ude95", "\ud83d\ude99", "\ud83d\ude8c", "\ud83d\ude8e", "\ud83d\ude93",
        "\ud83d\ude91", "\ud83d\ude92", "\ud83d\ude9a", "\ud83d\ude9c", "\ud83d\udef5", "\ud83d\udeb2",
        "\ud83d\udef4", "\ud83d\ude8f", "\ud83d\udea8", "\u2708\ufe0f", "\ud83d\udeeb", "\ud83d\udeec",
        "\ud83d\ude81", "\u26f5", "\ud83d\udea4", "\ud83d\udea2", "\ud83d\ude80", "\ud83d\udef8",
        "\ud83d\uddfc", "\ud83d\uddfd", "\ud83c\udff0", "\ud83c\udfef", "\ud83c\udfe0", "\ud83c\udfe1",
        "\ud83c\udfe2", "\ud83c\udfec", "\ud83c\udfe5", "\ud83c\udfeb", "\u26f2", "\u26fa",
        "\ud83c\udf05", "\ud83c\udf06", "\ud83c\udf07", "\ud83c\udf09", "\ud83e\udded", "\ud83d\uddff",
    };

    private static final String[] OBJECTS = {
        "\u231a", "\ud83d\udcf1", "\ud83d\udcbb", "\u2328\ufe0f", "\ud83d\udcbd", "\ud83d\udcbe",
        "\ud83d\udcbf", "\ud83d\udcf7", "\ud83d\udcf9", "\ud83d\udcfa", "\ud83d\udcfb", "\u23f0",
        "\u231b", "\ud83d\udca1", "\ud83d\udd26", "\ud83d\udcd4", "\ud83d\udcd5", "\ud83d\udcd7",
        "\ud83d\udcda", "\ud83d\udcd6", "\ud83d\udd16", "\ud83d\udcb0", "\ud83d\udcb5", "\ud83d\udcb3",
        "\ud83d\udc8e", "\ud83d\udd27", "\ud83d\udd28", "\u2699\ufe0f", "\ud83d\udd12", "\ud83d\udd11",
        "\ud83d\udeaa", "\ud83d\udec1", "\ud83e\uddf9", "\ud83e\uddfa", "\ud83e\uddfd", "\ud83d\udce6",
        "\ud83d\udceb", "\u2709\ufe0f", "\ud83d\udcdd", "\u270f\ufe0f", "\ud83d\udcce", "\ud83d\udccc",
        "\u2702\ufe0f", "\ud83d\udcca", "\ud83d\udcc8", "\ud83d\udcc5", "\ud83d\udcbc", "\ud83c\udf81",
    };

    private static final String[] SYMBOLS = {
        "\u2764\ufe0f", "\ud83e\udde1", "\ud83d\udc9b", "\ud83d\udc9a", "\ud83d\udc99", "\ud83d\udc9c",
        "\ud83d\udda4", "\ud83e\udd0d", "\ud83d\udc94", "\ud83d\udc95", "\ud83d\udc9e", "\ud83d\udc93",
        "\ud83d\udc97", "\ud83d\udc96", "\ud83d\udc98", "\ud83d\udc9d", "\u2763\ufe0f", "\ud83d\udcaf",
        "\u2705", "\u274c", "\u2757", "\u2753", "\u26a0\ufe0f", "\ud83d\udeab",
        "\u267b\ufe0f", "\ud83d\udd31", "\u269b\ufe0f", "\u2734\ufe0f", "\ud83c\udd95", "\ud83c\udd93",
        "\ud83d\udd1d", "\ud83d\udd1a", "\u25b6\ufe0f", "\u23f8\ufe0f", "\u23f9\ufe0f", "\ud83d\udd00",
        "\u2795", "\u2796", "\u2797", "\u267e\ufe0f", "\u00a9\ufe0f", "\u00ae\ufe0f",
        "\u2122\ufe0f", "\ud83d\udcac", "\ud83d\udcad", "\ud83d\udca4", "\ud83d\udca5", "\ud83c\udf89",
    };

    private static final String[] FLAGS = {
        "\ud83c\udfc1", "\ud83d\udea9", "\ud83c\udff4", "\ud83c\udff3\ufe0f", "\ud83c\uddee\ud83c\uddf3", "\ud83c\uddfa\ud83c\uddf8",
        "\ud83c\uddec\ud83c\udde7", "\ud83c\udde8\ud83c\udde6", "\ud83c\udde6\ud83c\uddfa", "\ud83c\udde9\ud83c\uddea", "\ud83c\uddeb\ud83c\uddf7", "\ud83c\uddef\ud83c\uddf5",
        "\ud83c\udde8\ud83c\uddf3", "\ud83c\uddf0\ud83c\uddf7", "\ud83c\udde7\ud83c\uddf7", "\ud83c\uddee\ud83c\uddf9", "\ud83c\uddea\ud83c\uddf8", "\ud83c\uddf7\ud83c\uddfa",
        "\ud83c\uddf2\ud83c\uddfe", "\ud83c\uddf8\ud83c\uddec", "\ud83c\udde6\ud83c\uddea", "\ud83c\uddf8\ud83c\udde6", "\ud83c\uddff\ud83c\udde6", "\ud83c\uddf3\ud83c\uddf5",
    };

    /** Tab glyphs, in the order the picker shows them. Recents is prepended by the view. */
    static final String[] TAB_LABELS = {
        "\ud83d\ude42", "\ud83c\udf3f", "\ud83c\udf75", "\u26bd", "\ud83d\ude97", "\ud83d\udca1",
        "\ud83d\udd23", "\ud83c\udff3\ufe0f",
    };

    static final String[] CATEGORY_NAMES = {
        "\u0053\u006d\u0069\u006c\u0065\u0079\u0073", "\u004e\u0061\u0074\u0075\u0072\u0065", "\u0046\u006f\u006f\u0064", "\u0041\u0063\u0074\u0069\u0076\u0069\u0074\u0079", "\u0054\u0072\u0061\u0076\u0065\u006c", "\u004f\u0062\u006a\u0065\u0063\u0074\u0073",
        "\u0053\u0079\u006d\u0062\u006f\u006c\u0073", "\u0046\u006c\u0061\u0067\u0073",
    };

    static final String[][] CATEGORIES = {
        SMILEYS, NATURE, FOOD, ACTIVITY, TRAVEL, OBJECTS, SYMBOLS, FLAGS,
    };
}
