package com.harithkavish.keyboard;

/**
 * What the keyboard knows before it has learnt anything from the person using
 * it. Everything here is a starting point that learning then moves: a seed word
 * carries a small weight so a word typed twice by hand outranks it.
 *
 * <p>The word list is ordered, and that order IS the frequency ranking -- index
 * 0 is the commonest word. It is deliberately small. A real dictionary would be
 * megabytes and would need a binary format and a loader; a few hundred words
 * covers the common case for prediction and gives autocorrect enough to check
 * against, which is as far as this keyboard tries to go.
 *
 * <p>Generated by tools/gen_vocab.py. Edit that, not this.
 */
final class Vocabulary {

    private Vocabulary() {
    }

    /** Space separated, commonest first. */
    static final String WORDS =
            ""
            + "the be to of and a in that have "
            + "i it for not on with he as you "
            + "do at this but his by from they we "
            + "say her she or an will my one all "
            + "would there their what so up out if about "
            + "who get which go me when make can like "
            + "time no just him know take people into year "
            + "your good some could them see other than then "
            + "now look only come its over think also back "
            + "after use two how our work first well way "
            + "even new want because any these give day most "
            + "us is are was were been has had did "
            + "does am being hello hi hey thanks thank please "
            + "sorry yes yeah okay ok sure right left today "
            + "tomorrow yesterday morning evening night week month weekend here "
            + "where why home house car food water coffee tea "
            + "lunch dinner breakfast love hate happy sad tired great "
            + "awesome cool nice bad better best worse call text "
            + "message send reply email phone number address name meeting "
            + "project team office boss client deadline update report going "
            + "coming leaving arriving waiting looking talking working running walking "
            + "need try keep let put ask tell feel seem "
            + "leave move turn start stop much many more less "
            + "little big small long short high low old young "
            + "really very quite pretty almost always never sometimes often "
            + "usually maybe something anything nothing everything someone anyone everyone "
            + "nobody should might must shall may cant dont didnt "
            + "wont isnt arent finish finished done ready problem question "
            + "answer idea plan family friend friends mother father brother "
            + "sister son daughter baby money price cost cheap free "
            + "buy sell pay order delivery shipping school college class "
            + "exam test study learn teach student teacher game play "
            + "watch movie music song book read write draw photo "
            + "picture train bus flight ticket hotel trip travel holiday "
            + "vacation beach birthday party wedding gift congratulations welcome goodbye "
            + "goodnight sleep wake eat drink cook clean wash open "
            + "close hospital doctor medicine health sick fever cold pain "
            + "rest code build deploy release bug fix issue branch "
            + "commit merge review ";

    /** Each entry is "first second": seeds for next-word prediction. */
    static final String[] BIGRAMS = {
        "i am",
        "i will",
        "i have",
        "i was",
        "i think",
        "i want",
        "i need",
        "i dont",
        "i just",
        "i know",
        "thank you",
        "thanks for",
        "how are",
        "are you",
        "how is",
        "what is",
        "what are",
        "where are",
        "see you",
        "talk to",
        "to you",
        "let me",
        "let us",
        "me know",
        "on my",
        "my way",
        "in the",
        "on the",
        "at the",
        "to the",
        "of the",
        "for the",
        "with the",
        "from the",
        "this is",
        "that is",
        "it is",
        "there is",
        "here is",
        "good morning",
        "good night",
        "good evening",
        "good luck",
        "happy birthday",
        "see you",
        "you later",
        "you soon",
        "we can",
        "we will",
        "we should",
        "you can",
        "you should",
        "you are",
        "you have",
        "do you",
        "did you",
        "can you",
        "will you",
        "would you",
        "going to",
        "want to",
        "need to",
        "have to",
        "trying to",
        "about the",
        "because of",
        "as well",
        "a lot",
        "lot of",
        "kind of",
        "sort of",
        "right now",
        "just now",
        "last week",
        "next week",
        "the meeting",
        "the project",
        "the report",
        "the code",
        "call you",
        "send the",
        "send you",
        "check the",
        "no problem",
        "no worries",
        "of course",
        "by the",
        "the way",
        "take care",
        "have a",
        "a good",
        "looking forward",
        "forward to",
        "sounds good",
    };

    /** Flat pairs: word, emoji, word, emoji. */
    static final String[] EMOJI_SEED = {
        "love", "\u2764\ufe0f",
        "heart", "\u2764\ufe0f",
        "happy", "\ud83d\ude0a",
        "sad", "\ud83d\ude22",
        "cry", "\ud83d\ude2d",
        "laugh", "\ud83d\ude02",
        "funny", "\ud83d\ude02",
        "fire", "\ud83d\udd25",
        "hot", "\ud83d\udd25",
        "birthday", "\ud83c\udf82",
        "party", "\ud83c\udf89",
        "congratulations", "\ud83c\udf89",
        "congrats", "\ud83c\udf89",
        "thanks", "\ud83d\ude4f",
        "thank", "\ud83d\ude4f",
        "please", "\ud83d\ude4f",
        "sorry", "\ud83d\ude14",
        "ok", "\ud83d\udc4d",
        "okay", "\ud83d\udc4d",
        "good", "\ud83d\udc4d",
        "great", "\ud83d\udd25",
        "awesome", "\ud83e\udd29",
        "cool", "\ud83d\ude0e",
        "nice", "\ud83d\udc4c",
        "food", "\ud83c\udf55",
        "lunch", "\ud83c\udf5d",
        "dinner", "\ud83c\udf7d",
        "coffee", "\u2615",
        "tea", "\ud83c\udf75",
        "beer", "\ud83c\udf7a",
        "pizza", "\ud83c\udf55",
        "cake", "\ud83c\udf70",
        "sleep", "\ud83d\ude34",
        "tired", "\ud83d\ude34",
        "sun", "\u2600\ufe0f",
        "rain", "\ud83c\udf27",
        "dog", "\ud83d\udc36",
        "cat", "\ud83d\udc31",
        "money", "\ud83d\udcb0",
        "work", "\ud83d\udcbc",
        "home", "\ud83c\udfe0",
        "car", "\ud83d\ude97",
        "music", "\ud83c\udfb5",
        "song", "\ud83c\udfb5",
        "star", "\u2b50",
        "angry", "\ud83d\ude20",
        "hug", "\ud83e\udd17",
        "kiss", "\ud83d\ude18",
        "wow", "\ud83d\ude2e",
        "yes", "\u2705",
        "no", "\u274c",
        "hello", "\ud83d\udc4b",
        "hi", "\ud83d\udc4b",
        "hey", "\ud83d\udc4b",
        "bye", "\ud83d\udc4b",
        "goodbye", "\ud83d\udc4b",
        "night", "\ud83c\udf19",
        "goodnight", "\ud83c\udf19",
        "morning", "\ud83c\udf05",
        "miss", "\ud83e\udd7a",
        "beautiful", "\ud83d\ude0d",
        "wedding", "\ud83d\udc8d",
        "baby", "\ud83d\udc76",
        "gift", "\ud83c\udf81",
        "travel", "\u2708\ufe0f",
        "flight", "\u2708\ufe0f",
        "book", "\ud83d\udcda",
        "game", "\ud83c\udfae",
        "win", "\ud83c\udfc6",
        "football", "\u26bd",
        "movie", "\ud83c\udfac",
        "photo", "\ud83d\udcf7",
        "idea", "\ud83d\udca1",
        "bug", "\ud83d\udc1b",
        "done", "\u2705",
        "ready", "\ud83d\ude80",
        "deploy", "\ud83d\ude80",
        "hundred", "\ud83d\udcaf",
    };
}
