# -*- coding: utf-8 -*-
"""Appends the keyword table to Emoji.java.

Modelled on CLDR emoji annotations: every emoji carries a short name plus
synonyms, and a search matches any of them. That is what makes "smile", "smiley"
and "grin" all reach the same face, and it is what the first version lacked --
it had one word per emoji, so anything but that exact word found nothing.

Run via gen_emoji.py, which calls into this.
"""

# emoji -> keywords, commonest term first. Kept to the emoji the picker offers.
KEYWORDS = {
    # --- faces: the ones people actually reach for -------------------------
    "\U0001F600": ["grin", "grinning", "smile", "smiley", "happy", "face", "haha"],
    "\U0001F603": ["smiley", "smile", "happy", "grin", "joy", "cheerful"],
    "\U0001F604": ["smile", "smiley", "happy", "grin", "laugh", "pleased"],
    "\U0001F601": ["beam", "grin", "smile", "smiley", "happy"],
    "\U0001F606": ["laugh", "laughing", "lol", "haha", "smile", "squint"],
    "\U0001F605": ["sweat", "relief", "phew", "nervous", "smile"],
    "\U0001F923": ["rofl", "rolling", "laugh", "laughing", "lol", "lmao", "funny", "hilarious"],
    "\U0001F602": ["joy", "laugh", "laughing", "lol", "crying", "funny", "tears", "haha"],
    "\U0001F642": ["slight", "smile", "smiley", "happy", "fine", "ok"],
    "\U0001F643": ["upside", "down", "silly", "sarcasm", "irony"],
    "\U0001F609": ["wink", "winking", "flirt", "joke", "smile"],
    "\U0001F60A": ["blush", "smile", "smiley", "happy", "shy", "pleased", "nice"],
    "\U0001F607": ["halo", "angel", "innocent", "saint", "good"],
    "\U0001F970": ["hearts", "love", "adore", "smitten", "cute"],
    "\U0001F60D": ["love", "heart", "eyes", "adore", "crush", "beautiful", "gorgeous"],
    "\U0001F929": ["star", "struck", "amazed", "wow", "awesome", "excited"],
    "\U0001F618": ["kiss", "blow", "love", "flirt", "mwah", "xoxo"],
    "\U0001F617": ["kiss", "kissing", "peck"],
    "\U0001F60B": ["yum", "delicious", "tasty", "tongue", "savour", "hungry"],
    "\U0001F61B": ["tongue", "cheeky", "silly", "tease"],
    "\U0001F61C": ["wink", "tongue", "cheeky", "crazy", "joke", "silly"],
    "\U0001F92A": ["zany", "crazy", "wild", "goofy", "silly"],
    "\U0001F60E": ["cool", "sunglasses", "shades", "awesome", "smug", "confident"],
    "\U0001F973": ["party", "celebrate", "hat", "birthday", "congrats", "horn"],
    "\U0001F60F": ["smirk", "smug", "sly", "suggestive"],
    "\U0001F612": ["unamused", "annoyed", "meh", "unimpressed", "bored"],
    "\U0001F61E": ["sad", "disappointed", "down", "unhappy", "frown"],
    "\U0001F614": ["pensive", "sad", "sorry", "tired", "dejected"],
    "\U0001F61F": ["worried", "anxious", "concerned", "nervous"],
    "\U0001F625": ["sad", "disappointed", "relieved", "upset"],
    "\U0001F622": ["cry", "crying", "sad", "tear", "tears", "upset", "sob"],
    "\U0001F62D": ["sob", "cry", "crying", "bawling", "sad", "tears", "devastated"],
    "\U0001F631": ["scream", "shock", "shocked", "fear", "scared", "omg", "horror"],
    "\U0001F633": ["flushed", "embarrassed", "shy", "blush", "surprised"],
    "\U0001F97A": ["pleading", "puppy", "eyes", "please", "beg", "cute", "sad"],
    "\U0001F624": ["triumph", "annoyed", "frustrated", "steam", "angry"],
    "\U0001F620": ["angry", "mad", "annoyed", "cross", "grumpy"],
    "\U0001F621": ["rage", "furious", "angry", "mad", "livid"],
    "\U0001F914": ["think", "thinking", "hmm", "consider", "wonder", "doubt"],
    "\U0001F92D": ["oops", "giggle", "secret", "quiet", "hand", "mouth"],
    "\U0001F92B": ["shush", "quiet", "secret", "hush", "silence"],
    "\U0001F910": ["zipper", "quiet", "silence", "speechless", "lips", "sealed"],
    "\U0001F60C": ["relieved", "calm", "content", "peaceful", "relax"],
    "\U0001F644": ["roll", "eyes", "whatever", "annoyed", "sarcasm"],
    "\U0001F62A": ["sleepy", "tired", "exhausted", "weary"],
    "\U0001F634": ["sleep", "sleeping", "sleepy", "tired", "zzz", "night", "bed"],
    "\U0001F927": ["sneeze", "sick", "cold", "tissue", "ill"],
    "\U0001F912": ["sick", "ill", "thermometer", "fever", "unwell"],
    "\U0001F915": ["hurt", "injured", "bandage", "pain", "ouch"],
    "\U0001F911": ["money", "rich", "cash", "dollar", "greedy", "profit"],
    "\U0001F917": ["hug", "hugging", "hugs", "embrace", "thanks", "care"],
    "\U0001F636": ["blank", "speechless", "expressionless", "silent", "nothing"],

    # --- hands -------------------------------------------------------------
    "\U0001F44D": ["thumbs", "thumbsup", "up", "yes", "ok", "okay", "good", "like",
                   "approve", "agree", "nice", "great"],
    "\U0001F44E": ["thumbs", "thumbsdown", "down", "no", "bad", "dislike", "disapprove"],
    "\U0001F44C": ["ok", "okay", "perfect", "good", "fine", "nice", "great"],
    "✌️": ["peace", "victory", "two", "v"],
    "\U0001F91E": ["fingers", "crossed", "luck", "hope", "wish", "lucky"],
    "\U0001F44F": ["clap", "clapping", "applause", "bravo", "well", "done", "congrats"],
    "\U0001F64F": ["please", "thanks", "thank", "pray", "prayer", "grateful", "namaste",
                   "sorry", "beg"],
    "\U0001F4AA": ["strong", "muscle", "flex", "strength", "power", "gym", "workout"],
    "\U0001F44B": ["wave", "hello", "hi", "hey", "bye", "goodbye", "greeting", "welcome"],
    "\U0001F91D": ["handshake", "deal", "agree", "partner", "shake", "hands"],
    "✍️": ["write", "writing", "note", "sign", "pen"],
    "\U0001F64C": ["celebrate", "praise", "hooray", "yay", "raise", "hands", "hurray"],

    # --- hearts and symbols -------------------------------------------------
    "❤️": ["heart", "love", "red", "romance", "like", "adore"],
    "\U0001F9E1": ["heart", "orange", "love"],
    "\U0001F49B": ["heart", "yellow", "love", "friendship"],
    "\U0001F49A": ["heart", "green", "love"],
    "\U0001F499": ["heart", "blue", "love"],
    "\U0001F49C": ["heart", "purple", "love"],
    "\U0001F5A4": ["heart", "black", "love"],
    "\U0001F90D": ["heart", "white", "love"],
    "\U0001F494": ["broken", "heart", "breakup", "sad", "heartbreak"],
    "\U0001F495": ["hearts", "love", "two"],
    "\U0001F49E": ["hearts", "love", "revolving"],
    "\U0001F493": ["heart", "beating", "love", "pulse"],
    "\U0001F497": ["heart", "growing", "love"],
    "\U0001F496": ["heart", "sparkling", "love"],
    "\U0001F498": ["cupid", "heart", "arrow", "love", "valentine"],
    "\U0001F49D": ["heart", "gift", "ribbon", "love"],
    "\U0001F4AF": ["hundred", "100", "perfect", "score", "full", "marks", "agree"],
    "✅": ["tick", "tickmark", "check", "checkmark", "done", "yes", "correct",
               "complete", "completed", "finished", "ok", "approved", "right"],
    "❌": ["cross", "no", "wrong", "incorrect", "cancel", "delete", "error", "fail"],
    "❗": ["exclamation", "important", "warning", "alert", "urgent"],
    "❓": ["question", "ask", "confused", "why", "what", "help"],
    "⚠️": ["warning", "caution", "alert", "careful", "danger"],
    "\U0001F6AB": ["no", "forbidden", "banned", "prohibited", "stop", "not"],
    "\U0001F195": ["new", "fresh", "latest"],
    "\U0001F51D": ["top", "up", "best", "above"],
    "\U0001F4AC": ["speech", "comment", "chat", "talk", "message", "say"],
    "\U0001F4AD": ["thought", "think", "bubble", "dream", "idea"],
    "\U0001F4A4": ["sleep", "zzz", "sleeping", "tired", "snore", "bed"],
    "\U0001F4A5": ["boom", "explosion", "bang", "collision", "blast", "wow"],
    "\U0001F389": ["party", "celebrate", "congrats", "congratulations", "tada", "hooray",
                   "birthday", "yay", "woohoo", "popper"],

    # --- nature and weather -------------------------------------------------
    "\U0001F436": ["dog", "puppy", "pet", "doggy", "animal"],
    "\U0001F431": ["cat", "kitten", "kitty", "pet", "animal", "meow"],
    "\U0001F98A": ["fox", "animal"],
    "\U0001F43B": ["bear", "animal"],
    "\U0001F43C": ["panda", "bear", "animal"],
    "\U0001F981": ["lion", "animal", "brave"],
    "\U0001F438": ["frog", "animal", "toad"],
    "\U0001F427": ["penguin", "animal", "bird"],
    "\U0001F41D": ["bee", "honey", "insect", "buzz"],
    "\U0001F98B": ["butterfly", "insect", "pretty"],
    "\U0001F41E": ["bug", "ladybird", "ladybug", "insect", "beetle", "issue"],
    "\U0001F984": ["unicorn", "magic", "fantasy", "rainbow"],
    "\U0001F332": ["tree", "evergreen", "pine", "forest", "christmas"],
    "\U0001F333": ["tree", "forest", "nature", "green"],
    "\U0001F334": ["palm", "tree", "beach", "holiday", "tropical", "vacation"],
    "\U0001F33F": ["herb", "plant", "leaf", "green", "nature"],
    "\U0001F340": ["clover", "luck", "lucky", "four", "leaf", "irish"],
    "\U0001F341": ["maple", "leaf", "autumn", "fall", "canada"],
    "\U0001F337": ["tulip", "flower", "spring"],
    "\U0001F338": ["blossom", "cherry", "flower", "sakura", "spring", "pink"],
    "\U0001F339": ["rose", "flower", "love", "romance", "red"],
    "\U0001F33B": ["sunflower", "flower", "sun", "yellow", "summer"],
    "\U0001F33C": ["daisy", "flower", "blossom"],
    "\U0001F490": ["bouquet", "flowers", "gift", "romance", "thanks"],
    "\U0001F31E": ["sun", "sunny", "hot", "summer", "bright", "day", "weather"],
    "\U0001F31D": ["moon", "night", "face"],
    "\U0001F31A": ["moon", "night", "new"],
    "⭐": ["star", "favourite", "favorite", "rating", "best"],
    "\U0001F31F": ["star", "glow", "shining", "sparkle", "special"],
    "✨": ["sparkles", "sparkle", "shiny", "magic", "clean", "new", "special", "stars"],
    "⚡": ["lightning", "bolt", "zap", "power", "fast", "electric", "energy"],
    "\U0001F525": ["fire", "hot", "lit", "flame", "burn", "great", "awesome", "amazing"],
    "\U0001F308": ["rainbow", "pride", "colour", "color", "rain", "sky"],
    "☁️": ["cloud", "cloudy", "weather", "sky", "overcast"],
    "❄️": ["snow", "snowflake", "cold", "winter", "freeze", "ice"],
    "\U0001F30A": ["wave", "sea", "ocean", "water", "surf", "beach"],
    "\U0001F30D": ["earth", "world", "globe", "planet", "map", "global"],

    # --- food ---------------------------------------------------------------
    "\U0001F34E": ["apple", "fruit", "red", "healthy"],
    "\U0001F34C": ["banana", "fruit"],
    "\U0001F349": ["watermelon", "fruit", "summer", "melon"],
    "\U0001F347": ["grapes", "fruit", "wine"],
    "\U0001F353": ["strawberry", "fruit", "berry", "sweet"],
    "\U0001F345": ["tomato", "vegetable", "red"],
    "\U0001F35E": ["bread", "loaf", "bakery", "toast"],
    "\U0001F9C0": ["cheese", "dairy"],
    "\U0001F373": ["egg", "cooking", "breakfast", "fry", "fried"],
    "\U0001F354": ["burger", "hamburger", "food", "fastfood", "lunch"],
    "\U0001F35F": ["fries", "chips", "fastfood", "food"],
    "\U0001F355": ["pizza", "food", "italian", "slice", "lunch", "dinner"],
    "\U0001F32E": ["taco", "mexican", "food"],
    "\U0001F35D": ["pasta", "spaghetti", "noodles", "italian", "food", "dinner"],
    "\U0001F35C": ["noodles", "ramen", "soup", "food", "asian"],
    "\U0001F363": ["sushi", "japanese", "food", "fish"],
    "\U0001F368": ["icecream", "ice", "cream", "dessert", "sweet", "cold"],
    "\U0001F366": ["icecream", "ice", "cream", "dessert", "soft", "sweet"],
    "\U0001F370": ["cake", "dessert", "sweet", "slice", "birthday"],
    "\U0001F382": ["cake", "birthday", "celebrate", "candles", "party", "bday"],
    "\U0001F36B": ["chocolate", "sweet", "candy", "bar", "treat"],
    "\U0001F36C": ["candy", "sweet", "sweets", "treat", "lolly"],
    "\U0001F36F": ["honey", "sweet", "jar", "bee"],
    "☕": ["coffee", "tea", "hot", "drink", "cafe", "espresso", "morning", "cup",
               "break"],
    "\U0001F375": ["tea", "green", "drink", "hot", "cup", "matcha"],
    "\U0001F37A": ["beer", "drink", "pint", "pub", "cheers", "alcohol"],
    "\U0001F37B": ["cheers", "beers", "drink", "celebrate", "toast", "pub"],
    "\U0001F377": ["wine", "drink", "glass", "red", "alcohol"],

    # --- activity and objects ------------------------------------------------
    "⚽": ["football", "soccer", "ball", "sport", "game", "match"],
    "\U0001F3C0": ["basketball", "ball", "sport", "game", "hoops"],
    "\U0001F3C8": ["football", "american", "rugby", "ball", "sport"],
    "\U0001F3BE": ["tennis", "ball", "sport", "racket"],
    "\U0001F3AF": ["target", "dart", "bullseye", "goal", "aim", "focus"],
    "\U0001F3C6": ["trophy", "win", "winner", "award", "prize", "champion", "first",
                   "victory", "best"],
    "\U0001F947": ["gold", "medal", "first", "win", "winner", "1st"],
    "\U0001F3C5": ["medal", "award", "prize", "sport"],
    "\U0001F3A8": ["art", "paint", "palette", "creative", "design", "draw"],
    "\U0001F3AC": ["movie", "film", "cinema", "clapper", "action", "video"],
    "\U0001F3A4": ["mic", "microphone", "sing", "karaoke", "podcast", "speak"],
    "\U0001F3A7": ["headphones", "music", "listen", "audio", "sound"],
    "\U0001F3B5": ["music", "note", "song", "tune", "melody", "audio"],
    "\U0001F3B6": ["music", "notes", "song", "tune", "melody"],
    "\U0001F3AE": ["game", "gaming", "controller", "play", "console", "videogame"],
    "\U0001F3B2": ["dice", "game", "random", "luck", "chance", "roll"],
    "\U0001F4F1": ["phone", "mobile", "smartphone", "cell", "call", "device"],
    "\U0001F4BB": ["laptop", "computer", "work", "code", "coding", "pc", "macbook"],
    "⌚": ["watch", "time", "clock", "wrist"],
    "⏰": ["alarm", "clock", "time", "wake", "reminder", "late"],
    "⌛": ["hourglass", "time", "wait", "waiting", "timer", "sand"],
    "\U0001F4A1": ["idea", "bulb", "light", "lightbulb", "think", "bright", "suggestion"],
    "\U0001F4DA": ["books", "book", "read", "reading", "study", "library", "learn"],
    "\U0001F4D6": ["book", "read", "reading", "open", "study"],
    "\U0001F4B0": ["money", "cash", "bag", "rich", "salary", "payment", "funds"],
    "\U0001F4B5": ["money", "cash", "dollar", "note", "payment", "bill"],
    "\U0001F4B3": ["card", "credit", "payment", "pay", "bank", "debit"],
    "\U0001F48E": ["diamond", "gem", "jewel", "precious", "ring", "valuable"],
    "\U0001F527": ["wrench", "tool", "fix", "repair", "spanner", "maintenance"],
    "\U0001F528": ["hammer", "tool", "build", "fix", "repair"],
    "⚙️": ["gear", "settings", "cog", "config", "options", "engine"],
    "\U0001F512": ["lock", "locked", "secure", "security", "private", "password"],
    "\U0001F511": ["key", "unlock", "access", "password", "secret"],
    "\U0001F4E6": ["package", "box", "parcel", "delivery", "shipping", "order"],
    "✉️": ["email", "mail", "envelope", "letter", "message", "send"],
    "\U0001F4DD": ["note", "memo", "write", "notes", "document", "todo"],
    "✏️": ["pencil", "write", "edit", "draw", "note"],
    "✂️": ["scissors", "cut", "snip", "trim"],
    "\U0001F4CA": ["chart", "bar", "graph", "data", "stats", "analytics", "report"],
    "\U0001F4C8": ["chart", "graph", "up", "growth", "increase", "trending", "rising"],
    "\U0001F4C5": ["calendar", "date", "schedule", "meeting", "day", "plan"],
    "\U0001F4BC": ["briefcase", "work", "business", "job", "office", "career"],
    "\U0001F381": ["gift", "present", "birthday", "surprise", "box", "wrapped"],

    # --- travel and places ---------------------------------------------------
    "\U0001F697": ["car", "drive", "driving", "auto", "vehicle", "road"],
    "\U0001F695": ["taxi", "cab", "car", "ride"],
    "\U0001F68C": ["bus", "transport", "coach", "travel"],
    "\U0001F693": ["police", "car", "emergency", "siren"],
    "\U0001F692": ["fire", "engine", "truck", "emergency"],
    "\U0001F6B2": ["bike", "bicycle", "cycle", "cycling", "ride"],
    "✈️": ["plane", "flight", "fly", "flying", "travel", "airplane", "trip",
                     "holiday", "vacation", "airport"],
    "\U0001F680": ["rocket", "launch", "ship", "shipped", "deploy", "fast", "space",
                   "release", "boost", "go"],
    "\U0001F3E0": ["home", "house", "building", "place", "residence"],
    "\U0001F3E2": ["office", "building", "work", "company", "business"],
    "\U0001F3E5": ["hospital", "medical", "health", "clinic", "doctor"],
    "\U0001F3EB": ["school", "college", "education", "university", "class"],
    "\U0001F305": ["sunrise", "morning", "dawn", "sun", "day"],
    "\U0001F307": ["sunset", "evening", "dusk", "city", "sun"],
    "\U0001F3C1": ["finish", "flag", "race", "end", "done", "checkered", "complete"],
}
